In [1]:
import numpy as np

In [14]:
print(np.__version__)

1.21.3


In [2]:
import sys

In [5]:
a= np.array([1,2,3], dtype='int8')
b = np.array([[1,2,3,4,5], [5,6,7,8,9]])

In [8]:
print("Dimension of 'a':", a.ndim)

Dimension of 'a': 1


In [10]:
print("Dimension of 'b' :", b.ndim)

Dimension of 'b' : 2


In [11]:
b.shape

(2, 5)

In [12]:
b.itemsize

4

In [13]:
b.size

10

In [16]:
c = np.array([[1,3,2,4,2,1,4], [5,3,2,8,9,6,4]])
c.shape

(2, 7)

In [17]:
print(c)

[[1 3 2 4 2 1 4]
 [5 3 2 8 9 6 4]]


In [20]:
print(c[0])

[1 3 2 4 2 1 4]


In [21]:
print(c[0][2:5])

[2 4 2]


In [22]:
print(c[:])

[[1 3 2 4 2 1 4]
 [5 3 2 8 9 6 4]]


In [23]:
print(c[:][:])

[[1 3 2 4 2 1 4]
 [5 3 2 8 9 6 4]]


In [27]:
print(c[:,2])

[2 2]


In [1]:
print(c[0, 1:-1:2])

NameError: name 'c' is not defined